import { NextResponse } from 'next/server';

/**
 * GET /api/skill
 *
 * Serves the IDSS Shopping OpenClaw skill as a downloadable JavaScript file.
 * The IDSS_API_URL placeholder is substituted at serve-time with the actual
 * deployed backend URL from environment variables.
 *
 * OpenClaw users can:
 *   - Download it:  curl https://idss.vercel.app/api/skill -o idss-shopping.js
 *   - Install it:   tell OpenClaw "Install this skill from URL: https://idss.vercel.app/api/skill"
 */
export async function GET() {
  // siteUrl is the Vercel frontend — the skill calls our /api/* proxy routes
  // so all traffic passes through a single public entry point.
  const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://idss-backend-production.up.railway.app';
  // directApiUrl is the Railway backend — used only for endpoints that don't
  // yet have a Vercel proxy (e.g. /search/ebay).
  const directApiUrl = process.env.NEXT_PUBLIC_API_BASE_URL || 'https://idss-backend-production.up.railway.app';

  // Inline the skill content here so the build doesn't depend on reading a
  // file at runtime (Vercel serverless functions run from a read-only bundle).
  // When the skill file changes, update this template too.
  const skillContent = `/**
 * IDSS Shopping Assistant — OpenClaw Skill
 * Auto-generated by ${siteUrl}/api/skill
 *
 * Connects OpenClaw to the IDSS AI shopping backend.
 * Works with WhatsApp, iMessage, Telegram, Discord, Slack, Signal.
 *
 * Install: tell OpenClaw "Install this skill from URL: ${siteUrl}/api/skill"
 */

// AI chat routes through the Vercel proxy (/api/chat-text).
// eBay search goes directly to the Railway backend (/search/ebay).
const IDSS_CHAT_URL = '${siteUrl}/api/chat-text';
const IDSS_API_URL  = '${directApiUrl}';

// ── Text formatter (kept in skill for offline resilience) ─────────────────
function shortCpu(raw) {
  return raw.replace(/^(Intel Core |AMD |Apple )/i, '').slice(0, 22);
}

function formatText(data) {
  const lines = [];
  if (data.message) lines.push(data.message);
  if (data.response_type === 'recommendations' && data.recommendations?.length) {
    const products = data.recommendations.flat();
    if (products.length) {
      lines.push('', '📦 *Top Picks:*');
      products.slice(0, 5).forEach((p, i) => {
        const price = p.price != null ? \`$\${Number(p.price).toLocaleString()}\` : '';
        const specs = [
          p.laptop?.specs?.processor && shortCpu(p.laptop.specs.processor),
          p.laptop?.specs?.ram,
          p.laptop?.specs?.storage,
        ].filter(Boolean).join(' · ');
        lines.push(\`\\n\${i + 1}. *\${p.name || p.title}* \${price}\`);
        if (specs) lines.push(\`   \${specs}\`);
        if (p.rating) lines.push(\`   ⭐ \${Number(p.rating).toFixed(1)}\`);
      });
    }
  }
  if (data.quick_replies?.length) {
    lines.push('', '💬 *You can ask:*');
    data.quick_replies.slice(0, 3).forEach(q => lines.push(\`• \${q}\`));
  }
  return lines.join('\\n').trim();
}

// ── eBay URL builder ──────────────────────────────────────────────────────
function ebayUrl(query, maxPrice) {
  const base = \`https://www.ebay.com/sch/i.html?_nkw=\${encodeURIComponent(query)}&_sop=15\`;
  return maxPrice ? base + \`&_udhi=\${maxPrice}\` : base;
}

// ── Main skill ────────────────────────────────────────────────────────────
export default {
  name: 'IDSS Shopping Assistant',
  version: '1.2.0',
  description: 'AI shopping — find laptops, electronics, books. Compare. Get eBay deals.',

  triggers: [
    'find me', 'looking for', 'recommend', 'compare', 'which is better',
    ' vs ', 'laptop', 'macbook', 'tablet', 'gaming', 'work laptop',
    'buy', 'shop', 'deal', 'price', 'under $', 'budget',
    'ebay', 'best deal', 'worth the price', 'battery life',
  ],

  memory: { idss_session_id: 'string' },
  permissions: ['network', 'memory', 'browser'],

  async run({ message, memory, send, browse }) {
    const text = (message.text || '').trim();
    if (!text) return;

    const isEbay = /\\bebay\\b|best deal|cheapest listing/i.test(text);

    // ── eBay fast-path ────────────────────────────────────────────────────
    if (isEbay) {
      const budgetMatch = text.match(/under\\s*\\$?(\\d+)/i);
      const maxPrice = budgetMatch ? Number(budgetMatch[1]) : null;
      const query = text
        .replace(/\\bebay\\b|best deal|cheapest listing|under\\s*\\$?\\d+/gi, '')
        .replace(/\\b(find|search|look for|get me)\\b/gi, '')
        .trim();

      // Try our backend eBay endpoint first
      try {
        const params = new URLSearchParams({ q: query });
        if (maxPrice) params.set('max_price', String(maxPrice));
        const res = await fetch(\`\${IDSS_API_URL}/search/ebay?\${params}\`);
        const ebayData = await res.json();

        if (ebayData.results?.length) {
          let reply = \`🛒 *eBay listings for "\${query}":*\\n\`;
          ebayData.results.forEach((item, i) => {
            reply += \`\\n\${i + 1}. \${item.title}\`;
            if (item.price) reply += \` — \${item.price}\`;
            if (item.condition) reply += ' (' + item.condition + ')';
            if (item.shipping) reply += \`\\n   📦 \${item.shipping}\`;
            reply += \`\\n   \${item.url}\`;
          });
          await send(reply);
        } else if (browse && ebayData.search_url) {
          // URL-only fallback: OpenClaw browser scrapes the page
          await send(\`🔍 Searching eBay for "\${query}"...\`);
          const page = await browse.open(ebayData.search_url);
          const scraped = await page.extract({
            items: [{ title: '.s-item__title', price: '.s-item__price', url: 'a.s-item__link@href' }],
          });
          const items = (scraped.items || []).filter(i => i.title && !i.title.includes('Shop on eBay'));
          if (items.length) {
            let reply = \`🛒 *eBay: "\${query}"*\\n\`;
            items.slice(0, 5).forEach((item, i) => {
              reply += \`\\n\${i + 1}. \${item.title}\`;
              if (item.price) reply += \` — \${item.price}\`;
              if (item.url) reply += \`\\n   \${item.url}\`;
            });
            await send(reply);
          } else {
            await send(\`No eBay results. View directly: \${ebayData.search_url}\`);
          }
        } else {
          await send(\`Search eBay here: \${ebayUrl(query, maxPrice)}\`);
        }
      } catch {
        await send(\`Search eBay here: \${ebayUrl(query, maxPrice)}\`);
      }
      return;
    }

    // ── IDSS AI shopping ──────────────────────────────────────────────────
    let sessionId = await memory.get('idss_session_id');
    if (!sessionId) {
      sessionId = \`oc-\${Date.now()}-\${Math.random().toString(36).slice(2, 8)}\`;
      await memory.set('idss_session_id', sessionId, { ttl: 86400 });
    }

    try {
      const resp = await fetch(IDSS_CHAT_URL, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ message: text, session_id: sessionId }),
      });
      if (!resp.ok) throw new Error(\`HTTP \${resp.status}\`);
      const data = await resp.json();
      await send(data.text || 'No response from IDSS.');
    } catch (err) {
      await send(\`⚠️ Shopping assistant unavailable. (Error: \${err.message})\`);
    }
  },

  async onReset({ memory, send }) {
    await memory.delete('idss_session_id');
    await send('🔄 Shopping session reset. What are you looking for?');
  },
};
`;

  return new NextResponse(skillContent, {
    status: 200,
    headers: {
      'Content-Type': 'application/javascript; charset=utf-8',
      'Content-Disposition': 'attachment; filename="idss-shopping.js"',
      'Cache-Control': 'public, max-age=3600',
    },
  });
}
